### ISSUE TITLE
Fails to locate beacon

### ISSUE THREAD

**Issue by nickhough** [sibowler/brewpi-brewometer#1]
When scanning, this is the result I get. Any ideas?

![image](https://cloud.githubusercontent.com/assets/10394866/20761248/980b35c6-b6df-11e6-94e3-b18f2de7cee3.png)

**Comment by sibowler** [comment]
Hi @nickhough,

Has this recently started happening, or is this a new install?

Can you run the command `hcitool dev` and check that you get a device listed? If so, is the device hci0, or another number?

**Comment by nickhough** [comment]
Hey @sibowler -

This is a fresh install.

![image](https://cloud.githubusercontent.com/assets/10394866/20766822/28ef8ab4-b6f5-11e6-92b3-de74784430e4.png)

Appears no devices are recognized.

**Comment by nickhough** [comment]
I case anyone else runs into this, the following command solved my problem:

`sudo hciconfig hci0 up`

Found that here: http://raspberrypi.stackexchange.com/questions/12077/bluetooth-device-is-not-available
