### ISSUE TITLE
Corrections to GRAVITY.colour - avoid errors due to blank lines

### ISSUE THREAD

**Issue by fabriziorizzo** [sibowler/brewpi-brewometer#3]
Either fix the code in tilt-hydrometer.py to skip/filter blank lines in csv files, or Enhance GRAVITY.colour as follows:
1. add another instruction/warning in the comments
2. replace blank lines with empty comment lines
3. explicitly add an #EOF comment at end to avoid trailing empty lines

Enhancements Proposed to GRAVITY.colour:

```
#Gravity Calibration file for Tilt Hydrometer
#To be active, the file should be named GRAVITY.<colour> in the tiltHydrometer/ folder
#and have at least one calibration value inside.
#File must not have any blank lines.
#To calibrate a black tilt hydrometer, the file would be called GRAVITY.black
#The following example two calibration points are used. 
#0.997 read from the tilt hydrometer will be calibrated to the actual value of 0.999
#1.056 read from the tilt hydrometer will be calibrated to the actual value of 1.060
#Other calibration points will be calculated.
#
#Original SG Value, Calibrated Value
0.997, 0.999
1.056, 1.060
#EOF
```

**Comment by sibowler** [comment]
Fixed. Have added logic to skip invalid/blank lines. Also added logging so that skipped lines are logged to assist with debugging.

Changes in TiltHydrometer.py
