### ISSUE TITLE
404  Not Found [IP: 93.93.128.193 80] Error 

### ISSUE THREAD

**Issue by Groovetheory** [sibowler/brewpi-brewometer#4]
I am new to working with python and Raspberry Pi so forgive my lack of understanding.  I am trying to get my Tilt hydrometer working with the legacy brancy of Brew-Pi on a Pi 3 card.

**When I run the following command:**
sudo apt-get install bluez python-bluez python-scipy python-numpy libcap2-bin 

ipy python-numpy libcap2-bin
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcap2-bin is already the newest version.
python-numpy is already the newest version.
bluez is already the newest version.
bluez set to manually installed.
The following extra packages will be installed:
  python-imaging
The following NEW packages will be installed:
  python-bluez python-imaging python-scipy
0 upgraded, 3 newly installed, 0 to remove and 4 not upgraded.
Need to get 9,814 B/7,402 kB of archives.
After this operation, 29.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y

**I receive the following error:**

Err http://mirrordirector.raspbian.org/raspbian/ jessie/main python-imaging all 2.6.1-2+deb8u2
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/p/pillow/python-imaging_2.6.1-2+deb8u2_all.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I have tried to fix the issue, but I am not sure how to continue?  Any assistance would be greatly appreciated.

Groove

**Comment by sibowler** [comment]
I believe this error is caused because the apt mirrors no longer contain the python-imaging library for the version of raspbian that you are using. 

Try upgrading raspbian first by following the steps here: [Updating and Upgrading Raspbian](https://www.raspberrypi.org/documentation/raspbian/updating.md) and then re-running the brewpi mod install steps.

**Comment by Groovetheory** [comment]
Thank you for your assistance. Last night I just formated another SD card,
downloaded Noobs, installed the updated version, loaded Brewpi, and your
files. Everything seems to be working now. I just need to determine where
your tilt folders/files go in the brewpi structure because I was in the
wrong directory when I used the Git command.  I was tired at that point.

I don't see any reason I should not get it running today or Monday.

Thank you for creating a great product.

Groove

On Mar 18, 2017 14:12, "sibowler" <notifications@github.com> wrote:

I believe this error is caused because the mirrors no longer contain the
python-imaging library for the version of raspbian that you are using.

Try upgrading raspbian first by following the steps here: Updating and
Upgrading Raspbian
<https://www.raspberrypi.org/documentation/raspbian/updating.md> and then
re-running the brewpi mod install steps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sibowler/brewpi-brewometer/issues/4#issuecomment-287575113>,
or mute the thread

**Comment by Groovetheory** [comment]
I have one more question.  So I have loaded Brewpi 3 times now the legacy
branch and an Arduino Uno and everything is working with the sensors and
SSRs.  Every time I load the Tilt files, I lose connection to the Uno
card.  I believe that the files you wrote are for the latest build for the
Spark, and this is the reason I have losing connection with he Uno
card.  Do you have a legacy branch files for the Tilt?  I run the sudo
~/brewpi-tools/updater.py --ask command and try to update the hex file on
the Uno card, but it does not resolve the issue.  This is the message I
receive in the view logs.


Mar 19 2017 21:26:05 Opening serial port
Mar 19 2017 21:26:05 Notification: Script started for beer 'My First BrewPi
Run'
Mar 19 2017 21:26:15 Checking software version on controller...
Mar 19 2017 21:26:15 Found BrewPi v0.2.8 build unknown, running on an
Arduino Uno with a revC shield on port /dev/ttyACM0

Mar 19 2017 21:26:15 Warning: minimum BrewPi version compatible with this
script is 0.4.0 but version number received is 0.2.8

ERROR: the newest version of BrewPi is not compatible with Arduino.
You can use our legacy branch with your Arduino, in which we only include
the backwards compatible changes.
To change to the legacy branch, run: sudo ~/brewpi-tools/updater.py --ask ,
and choose the legacy branch.

Thanks for everything.

Groove

**Comment by rebroad** [comment]
> I believe this error is caused because the apt mirrors no longer contain the python-imaging library for the version of raspbian that you are using.
> 
> Try upgrading raspbian first by following the steps here: [Updating and Upgrading Raspbian](https://www.raspberrypi.org/documentation/raspbian/updating.md) and then re-running the brewpi mod install steps.

Upgrading doesn't work. full-upgrade and dist-upgrade both fail. Any other suggestions please? Surely the files needed must be somewhere...

**Comment by lbussy** [comment]
I don’t want to hijack but I incorporated Tilt support (inspired by @sibowler) natively in [BrewPi Remix](https://www.brewpiremix.com).  Bluetooth python libs *are* a freaking mess and it took me a while to clean it up.   There is no “upgrade” path, but there is a hacky backup and restore which may work for you.  Or, if you do not need to keep your precious brew data, you can use the uninstall script and reinstall clean (safest.)
