### ISSUE TITLE
Not issue - Adding SG to BrewPi LCD Panel

### ISSUE THREAD

**Issue by kaljade** [sibowler/brewpi-brewometer#6]
Hi there,

As you can tell by the title it's not an issue, more of a enhancement request.

It would be great if the top line of the LCD panel on the BrewPi that currently displays 'Mode' could instead display 'Specific Gravity', or even better the ability to choose what to display on each row from the following options:

- Mode
- Beer temp (BrewPi sensor)
- Beer temp (Tilt sensor)
- Fridge temp (BrewPi sensor)
- Specific Gravity (Tilt sensor)
- Status

Cheers,

Kal

**Comment by sibowler** [comment]
Unfortunately it's not possible to write data back to the LCD display with the current Brewpi implementation. It's a great idea though!
